// The page template (B29-R9, R12 and decision 7): one self-contained HTML file. Pure string assembly.
import { createHash } from 'node:crypto';

export const LOGO = 'https://www.alterna.ca/media/t0onoi0m/alterna-savings.svg';
export const GENERATED = '<!-- GENERATED by help/build-help.mjs from COB-ts/docs/*.md. Do not edit. Run: node help/build-help.mjs -->';

/** Runs in the head, before first paint: picks the document from the hash (an unknown hash gives the manual). */
export const HEAD_SCRIPT =
  "(function () {\n  var m = /^#(?:doc-)?(manual|coverage|domain)(?:-|$)/.exec(location.hash.toLowerCase());\n" +
  "  var d = document.documentElement;\n  d.className = 'js';\n  d.setAttribute('data-doc', m ? m[1] : 'manual');\n}());\n";

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/** Status glyphs, one symbol per state (the chips refer to them with <use>). */
const SYMBOLS = {
  covered: '<path d="M2.5 6.5 5 9l4.5-5.5"/>',
  partial: '<circle cx="6" cy="6" r="4.75"/><path d="M6 1.25a4.75 4.75 0 0 0 0 9.5z" fill="currentColor"/>',
  planned: '<circle cx="6" cy="6" r="4.75"/><path d="M6 3.25V6l2 1.25"/>',
  wrong: '<path d="M6 1.5 11 10.25H1z"/><path d="M6 4.75v2.5M6 8.6v.2"/>',
  open: '<circle cx="6" cy="6" r="4.75" stroke-dasharray="2 2"/>',
  out: '<circle cx="6" cy="6" r="4.75"/><path d="M3.5 6h5"/>',
};
export const SPRITE_IDS = Object.keys(SYMBOLS).map((k) => `g-${k}`);
const sprite =
  '<svg class="sprite" aria-hidden="true" focusable="false"><defs>' +
  Object.entries(SYMBOLS).map(([k, v]) => `<symbol id="g-${k}" viewBox="0 0 12 12">${v}</symbol>`).join('') +
  '</defs></svg>';

/** The contents list of one document: H2 entries with their H3 entries one list level deeper. */
export function tocHtml(items) {
  const groups = [];
  for (const it of items) {
    if (it.level === 2 || groups.length === 0) groups.push({ head: it, kids: [] });
    else groups[groups.length - 1].kids.push(it);
  }
  const li = (it) => `<a href="#${it.id}">${esc(it.text)}</a>`;
  return (
    '<ul>' +
    groups
      .map((g) => `<li>${li(g.head)}${g.kids.length ? `<ul>${g.kids.map((k) => `<li>${li(k)}</li>`).join('')}</ul>` : ''}</li>`)
      .join('') +
    '</ul>'
  );
}

const b64 = (s) => createHash('sha256').update(s).digest('base64');

/**
 * docs: [{ key, label, sub, file, sha, title, toc, body }] in registry order.
 * Returns the full page text.
 */
export function assemblePage({ docs, ids, css, clientJs, fingerprint, builtOn }) {
  const scripts = [HEAD_SCRIPT, `\n${clientJs.replace(/\s+$/, '')}\n`];
  const csp =
    `default-src 'none'; script-src ${scripts.map((s) => `'sha256-${b64(s)}'`).join(' ')}; style-src 'unsafe-inline'; ` +
    `img-src https://www.alterna.ca data:; base-uri 'none'; form-action 'none'`;
  const json = JSON.stringify(fingerprint).replace(/</g, '\\u003c');
  const tabs = docs
    .map((d, i) => `<a href="#doc-${d.key}"${i === 0 ? ' aria-current="page"' : ''}>${esc(d.label)} <span class="sub">${esc(d.sub)}</span></a>`)
    .join('\n    ');
  const articles = docs
    .map(
      (d) =>
        `<article class="doc" id="doc-${d.key}" aria-labelledby="${d.key}-title">\n` +
        `<details class="toc-box" open><summary>Contents</summary>\n<nav aria-label="Contents of the ${esc(d.title)}">${tocHtml(d.toc)}</nav>\n</details>\n` +
        `<div class="doc-body">\n${d.body}</div>\n</article>`,
    )
    .join('\n');
  const stamps = docs.map((d) => `<code>${esc(d.file)}</code> (sha256 <code>${d.sha.slice(0, 12)}</code>)`).join('; ');
  return (
    `${GENERATED}\n<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n` +
    `<meta name="viewport" content="width=device-width, initial-scale=1">\n` +
    `<meta http-equiv="Content-Security-Policy" content="${csp}">\n` +
    `<title>Help - Alterna Cost of Borrowing calculator</title>\n<style>\n${css.replace(/\s+$/, '')}\n</style>\n<script>${HEAD_SCRIPT}</script>\n</head>\n<body>\n` +
    `<a class="skip" href="#doc-content">Skip to document</a>\n${sprite}\n` +
    `<noscript><p class="noscript">JavaScript is off. The three documents are shown one after the other; contents lists, links and printing still work.</p></noscript>\n` +
    `<header class="help-header">\n` +
    `  <span class="brand-logo"><img id="brandLogo" data-src="${LOGO}" alt="Alterna Savings" width="236" height="37"><span class="brand-fallback" hidden>Alterna Savings</span></span>\n` +
    `  <a class="btn-pill" href="/ui/ca.html">Back to calculator</a>\n</header>\n` +
    `<div class="doc-bar">\n  <nav class="doc-nav" aria-label="Documents">\n    ${tabs}\n  </nav>\n` +
    `  <div class="goto js-only"><label for="goto">Go to ID</label><input id="goto" type="search" list="id-index" placeholder="e.g. US-04, OQ-P, B24" autocomplete="off">` +
    `<p class="goto-msg" id="goto-msg" role="status"></p>\n<datalist id="id-index">${ids.map((i) => `<option value="${esc(i)}"></option>`).join('')}</datalist></div>\n</div>\n` +
    `<div class="help-shell">\n<p class="notice" id="notice" role="status"></p>\n<main id="doc-content">\n${articles}\n</main>\n</div>\n` +
    `<footer class="help-footer">\n<p>Built ${esc(builtOn)} (UTC) from ${stamps}.</p>\n` +
    `<p>The calculator tab you came from is still open; you can close this tab instead. Use the tabs above to search another document: your browser's Find reaches all three in Chrome.</p>\n</footer>\n` +
    `<p class="toast" id="live" role="status"></p>\n` +
    `<script type="application/json" id="help-build">${json}</script>\n<script>${scripts[1]}</script>\n</body>\n</html>\n`
  );
}
