import { describe, expect, it } from 'vitest';
import { calculateCobCanada } from '../../src/ca/index.js';
import { totalCashFees, totalFinancedFees } from '../../src/ca/fees.js';
import type { CobCanadaInput, FeeSchedule } from '../../src/ca/index.js';
import { wireToInput } from './support/builders.js';
import { relDiffFloor1 } from './support/compare.js';
import { loadFixture } from './support/fixtures.js';

/**
 * B1 (COB-architecture.md §5, 012 D-10, OQ-H / ADR-02): fee totals are the plain left-to-right
 * sum of fee.amount, with no rounding in the calculation path. QA red set, written before
 * the developer step (2026-09-27). Plain `it`: red today because fees.ts wraps each total
 * in round2.
 *
 * Every expected number comes from fixtures/b1_unrounded_fee_vectors.json, generated by
 * fixtures/generate_b1_unrounded_fee_vectors.py from the CalculateAll transliteration
 * (generate_t5_engine_rules.py, trust-checked == against REF-01 real Excel output and six
 * oracle vectors), with OQ-S (cash fees only in C / APR) and the engine's P (OQ-Q open).
 * NOT from this engine.
 */
const fx = loadFixture('b1_unrounded_fee_vectors.json') as {
  tolerance_rel: number;
  fee_limit: { cases: { id: string; loanAmount: number; financed: number[]; sum: number; accept: boolean }[] };
  vectors: {
    id: string;
    request: Record<string, unknown>;
    fee_totals: { financed: number; cash: number; all: number };
    totals: Record<string, number>;
    rows: Record<string, number | string>[];
  }[];
};
const REL = fx.tolerance_rel;
const rel = relDiffFloor1;
const expectRel = (a: number, e: number, what: string) =>
  expect(rel(a, e), `${what}: actual ${a}, expected ${e}`).toBeLessThanOrEqual(REL);

const toInput = (request: Record<string, unknown>): CobCanadaInput => wireToInput(request);

describe('B1 fee totals: plain unrounded left-to-right sums (fees.ts)', () => {
  const s: FeeSchedule = {
    fees: [
      { name: 'a', amount: 100.004, financed: true, includedInCob: true },
      { name: 'b', amount: 200.003, financed: true, includedInCob: false },
      { name: 'c', amount: 0.005, financed: false, includedInCob: true },
      { name: 'd', amount: 1234.565, financed: false, includedInCob: false },
      { name: 'e', amount: 0.001, financed: true, includedInCob: true },
    ],
  };
  it('each total equals its unrounded reduce sum exactly (toBe)', () => {
    expect(totalFinancedFees(s)).toBe(0 + 100.004 + 200.003 + 0.001);
    expect(totalCashFees(s)).toBe(0 + 0.005 + 1234.565);
  });
  it('sub-cent totals are not rounded to 0 or up to a cent', () => {
    const three = (financed: boolean): FeeSchedule => ({
      fees: [0.001, 0.001, 0.001].map((amount, i) => ({ name: `f${i}`, amount, financed, includedInCob: true })),
    });
    expect(totalFinancedFees(three(true))).toBe(0.001 + 0.001 + 0.001);
    expect(totalCashFees(three(false))).toBe(0.001 + 0.001 + 0.001);
    expect(totalCashFees({ fees: [{ name: 'x', amount: 0.005, financed: false, includedInCob: true }] })).toBe(0.005);
  });
});

describe('B1 end to end through calculateCobCanada (oracle vectors)', () => {
  describe.each(fx.vectors.map((v) => [v.id, v] as const))('%s', (_id, v) => {
    const res = () => calculateCobCanada(toInput(v.request));

    it('C (cobAmount) = total interest + unrounded financed + unrounded cash', () => {
      const r = res();
      expectRel(r.cobAmount, v.totals.cob_amount!, 'cobAmount');
      expectRel(r.cobAmount - r.totalInterest, v.fee_totals.all, 'cobAmount - totalInterest');
    });

    it('APR (cobRatePercent), engine P, general branch whenever the unrounded fee total > 0', () => {
      expectRel(res().cobRatePercent, v.totals.cob_rate_pct_engine_p!, 'cobRatePercent');
    });

    it('principal: disbursalAmount = loan - unrounded financed; principalPayment, feesRecovered, totals', () => {
      const r = res();
      expectRel(r.disbursalAmount, v.totals.disbursal_amount!, 'disbursalAmount');
      expectRel(r.amortizedPrincipal, v.request.loanAmount as number, 'amortizedPrincipal');
      expectRel(r.principalPayment, v.totals.principal_payment!, 'principalPayment');
      expectRel(r.feesRecovered, v.totals.fees_recovered!, 'feesRecovered');
      expectRel(r.totalInterest, v.totals.total_interest!, 'totalInterest');
      expectRel(r.totalPayment, v.totals.total_payment!, 'totalPayment');
      expectRel(r.endingBalance, v.totals.ending_balance!, 'endingBalance');
      expect(r.numberOfPayments).toBe(v.totals.n);
      expect(r.termDays).toBe(v.totals.term_days);
    });

    it('schedule rows match the oracle field by field (fees in and out of the waterfall)', () => {
      const rows = res().amortizationSchedule;
      expect(rows.length).toBe(v.rows.length);
      rows.forEach((row, i) => {
        const e = v.rows[i]!;
        const at = `row ${i + 1}`;
        expect(row.date.toISOString().slice(0, 10), at).toBe(e.date);
        expectRel(row.openingBalance, e.open_loan as number, `${at} openingBalance`);
        expectRel(row.feesOpening, e.open_fees as number, `${at} feesOpening`);
        expectRel(row.periodInterest, e.new_int as number, `${at} periodInterest`);
        expectRel(row.paymentAmount, e.payment as number, `${at} paymentAmount`);
        expectRel(row.interestPaid, e.interest_paid as number, `${at} interestPaid`);
        expectRel(row.feesPaid, e.fees_paid as number, `${at} feesPaid`);
        expectRel(row.principalPortion, e.principal_paid as number, `${at} principalPortion`);
        expectRel(row.feesClosing, e.close_fees as number, `${at} feesClosing`);
        expectRel(row.closingBalance, e.close_loan as number, `${at} closingBalance`);
      });
    });
  });
});

describe('B1 fee limit (BRD §6) uses the unrounded financed total', () => {
  const base = (loanAmount: number, financed: number[]): CobCanadaInput =>
    toInput({
      ...fx.vectors[0]!.request,
      loanAmount,
      fees: { fees: financed.map((amount, i) => ({ name: `F${i}`, amount, financed: true, includedInCob: true })) },
    });
  it.each(fx.fee_limit.cases.map((c) => [c.id, c] as const))('%s', (_id, c) => {
    const run = () => calculateCobCanada(base(c.loanAmount, c.financed));
    if (c.accept) expect(run).not.toThrow();
    else expect(run).toThrow(RangeError);
  });
});
