import { describe, expect, it } from 'vitest';
import { calculateCobCanada } from '../../src/ca/index.js';
import { validateCobCanadaInput } from '../../src/ca/validate.js';
import type { CobCanadaInput } from '../../src/ca/index.js';
import { wireToInput } from './support/builders.js';
import { loadFixture } from './support/fixtures.js';

/**
 * B2 (COB-architecture.md §5, 012 D-08, OQ-M decided): the fee limit counts financed AND
 * non-financed fees. Reject when (sum financed + sum non-financed) >= loanAmount (macro
 * ValidateInput lines 175-185, `If (finFee + nonFinFee) >= loanAmt`). QA red set, written
 * before the developer step (2026-09-27). Plain `it`: the `red_before_b2` cases are red today
 * because validate.ts counts financed fees only.
 *
 * Expected accept/reject comes from fixtures/b2_fee_limit_vectors.json, generated by
 * fixtures/generate_b2_fee_limit_vectors.py (macro transliteration, trust-checked against the
 * 012 D-08 expectations and the B1 fee_limit cases). NOT from this engine.
 *
 * The error MESSAGE is not pinned here; a rejection only has to be a RangeError whose message
 * mentions a fee, so an unrelated RangeError can't pass. The exact text (Q-MSG interim, decided
 * 2026-09-27) is pinned once, in validate.test.ts.
 */
const fx = loadFixture('b2_fee_limit_vectors.json') as {
  base_request: Record<string, unknown>;
  cases: {
    id: string;
    loanAmount: number;
    fees: { name: string; amount: number; financed: boolean; includedInCob: boolean }[];
    accept: boolean;
    red_before_b2: boolean;
    note: string;
  }[];
};

function input(c: (typeof fx.cases)[number]): CobCanadaInput {
  return wireToInput({ ...fx.base_request, loanAmount: c.loanAmount, fees: { fees: c.fees.map((f) => ({ ...f })) } });
}

function feeLimitError(fn: () => unknown): unknown {
  try {
    fn();
  } catch (e) {
    return e;
  }
  return undefined;
}

describe('B2 D-08 fee limit counts financed + non-financed fees (OQ-M, macro oracle)', () => {
  it('fixture has the expected shape (20 cases, 10 red before B2)', () => {
    expect(fx.cases.length).toBe(20);
    expect(fx.cases.filter((c) => c.red_before_b2).length).toBe(10);
  });

  for (const c of fx.cases) {
    const title = `${c.id}: ${c.accept ? 'accepted' : 'rejected'} (${c.note})`;
    if (c.accept) {
      it(title, () => {
        expect(() => validateCobCanadaInput(input(c))).not.toThrow();
        expect(() => calculateCobCanada(input(c))).not.toThrow();
      });
    } else {
      it(title, () => {
        for (const run of [() => validateCobCanadaInput(input(c)), () => calculateCobCanada(input(c))]) {
          const err = feeLimitError(run);
          expect(err, 'expected a RangeError').toBeInstanceOf(RangeError);
          expect((err as Error).message).toMatch(/fee/i);
        }
      });
    }
  }
});
